import {Post} from '../post';

const fakeDate = new Date();
fakeDate.setFullYear(2019);
fakeDate.setMonth(4);
fakeDate.setDate(10);
export const posts:Post[] = [
    {
        id:1,
        urlOfPost:'https://www.google.com.tw',
        date:fakeDate,
        categories:[
            {
                name:'分類一',
                url:'https://www.google.com.tw'
            },{
                name:'分類二',
                url:'https://www.google.com.tw'
            },{
                name:'分類三',
                url:'https://www.google.com.tw'
            }
        ],
        title:'諸葛亮舌戰群儒，魯子敬力排眾議',
        imageUrl:'/img/afternoon-tea-time.jpeg'
    },
    {
        id:2,
        urlOfPost:'https://www.google.com.tw',
        date:fakeDate,
        categories:[
            {
                name:'分類一',
                url:'https://www.google.com.tw'
            },{
                name:'分類二',
                url:'https://www.google.com.tw'
            },{
                name:'分類三',
                url:'https://www.google.com.tw'
            }
        ],
        title:'諸葛亮舌戰群儒，魯子敬力排眾議',
        imageUrl:'/img/bookcase.jpeg'
    },
    {
        id:3,
        urlOfPost:'https://www.google.com.tw',
        date:fakeDate,
        categories:[
            {
                name:'分類一',
                url:'https://www.google.com.tw'
            },{
                name:'分類二',
                url:'https://www.google.com.tw'
            },{
                name:'分類三',
                url:'https://www.google.com.tw'
            }
        ],
        tags:[
            {
                name:'標籤一',
                url:'https://www.google.com.tw'
            },{
                name:'標籤二',
                url:'https://www.google.com.tw'
            },{
                name:'標籤三',
                url:'https://www.google.com.tw'
            }
        ],
        title:'諸葛亮舌戰群儒，魯子敬力排眾議。',
        excerpt:'卻說魯肅、孔明辭了玄德、劉琦，登舟望柴桑郡來。二人在舟中共議，魯肅謂孔明曰：「先生見孫將軍，切不可實言曹操兵多將廣。」孔明曰：「不須子敬叮嚀，亮自有...卻說魯肅、孔明辭了玄德、劉琦，登舟望柴桑郡來。二人在舟中共議，魯肅謂孔明曰：「先生見孫將軍，切不可實言曹操兵多將廣。」孔明曰：「不須子敬叮嚀，亮自有。'
    },
    {
        id:4,
        urlOfPost:'https://www.google.com.tw',
        date:fakeDate,
        categories:[],
        tags:[
            {
                name:'標籤一',
                url:'https://www.google.com.tw'
            },{
                name:'標籤二',
                url:'https://www.google.com.tw'
            },{
                name:'標籤三',
                url:'https://www.google.com.tw'
            }
        ],
        title:'諸葛亮舌戰群儒，魯子敬力排眾議。',
        excerpt:'卻說魯肅、孔明辭了玄德、劉琦，登舟望柴桑郡來。二人在舟中共議，魯肅謂孔明曰：「先生見孫將軍，切不可實言曹操兵多將廣。」孔明曰：「不須子敬叮嚀，亮自有...'
    },
    {
        id:5,
        urlOfPost:'https://www.google.com.tw',
        date:fakeDate,
        categories:[
            {
                name:'分類一',
                url:'https://www.google.com.tw'
            },{
                name:'分類二',
                url:'https://www.google.com.tw'
            },{
                name:'分類三',
                url:'https://www.google.com.tw'
            },{
                name:'分類一',
                url:'https://www.google.com.tw'
            },{
                name:'分類二',
                url:'https://www.google.com.tw'
            },{
                name:'分類三',
                url:'https://www.google.com.tw'
            },{
                name:'分類一',
                url:'https://www.google.com.tw'
            },{
                name:'分類二',
                url:'https://www.google.com.tw'
            },{
                name:'分類三',
                url:'https://www.google.com.tw'
            },{
                name:'分類一',
                url:'https://www.google.com.tw'
            },{
                name:'分類二',
                url:'https://www.google.com.tw'
            },{
                name:'分類三',
                url:'https://www.google.com.tw'
            },{
                name:'分類一',
                url:'https://www.google.com.tw'
            },{
                name:'分類二',
                url:'https://www.google.com.tw'
            },{
                name:'分類三',
                url:'https://www.google.com.tw'
            },{
                name:'分類一',
                url:'https://www.google.com.tw'
            },{
                name:'分類二',
                url:'https://www.google.com.tw'
            },{
                name:'分類三',
                url:'https://www.google.com.tw'
            },{
                name:'分類一',
                url:'https://www.google.com.tw'
            },{
                name:'分類二',
                url:'https://www.google.com.tw'
            },{
                name:'分類三',
                url:'https://www.google.com.tw'
            }
        ],
        title:'諸葛亮舌戰群儒，魯子敬力排眾議',
        imageUrl:'/img/glimpse-of-code.png'
    },{
        id:6,
        urlOfPost:'https://www.google.com.tw',
        date:fakeDate,
        categories:[
            {
                name:'分類一',
                url:'https://www.google.com.tw'
            },{
                name:'分類二',
                url:'https://www.google.com.tw'
            },{
                name:'分類三',
                url:'https://www.google.com.tw'
            }
        ],
        title:'諸葛亮舌戰群儒，魯子敬力排眾議。諸葛亮舌戰群儒，魯子敬力排眾議。',
        imageUrl:'/img/bookcase.jpeg'
    },
    {
        id:7,
        urlOfPost:'https://www.google.com.tw',
        date:fakeDate,
        categories:[{
                name:'分類一',
                url:'https://www.google.com.tw'
            },{
                name:'分類二',
                url:'https://www.google.com.tw'
            },{
                name:'分類三',
                url:'https://www.google.com.tw'
            },{
                name:'分類一',
                url:'https://www.google.com.tw'
            },{
                name:'分類二',
                url:'https://www.google.com.tw'
            },{
                name:'分類三',
                url:'https://www.google.com.tw'
            },{
                name:'分類一',
                url:'https://www.google.com.tw'
            },{
                name:'分類二',
                url:'https://www.google.com.tw'
            },{
                name:'分類三',
                url:'https://www.google.com.tw'
            },{
                name:'分類一',
                url:'https://www.google.com.tw'
            },{
                name:'分類二',
                url:'https://www.google.com.tw'
            },{
                name:'分類三',
                url:'https://www.google.com.tw'
            },{
                name:'分類一',
                url:'https://www.google.com.tw'
            },{
                name:'分類二',
                url:'https://www.google.com.tw'
            },{
                name:'分類三',
                url:'https://www.google.com.tw'
            },{
                name:'分類一',
                url:'https://www.google.com.tw'
            },{
                name:'分類二',
                url:'https://www.google.com.tw'
            },{
                name:'分類三',
                url:'https://www.google.com.tw'
            }
        ],
        tags:[],
        title:'諸葛亮舌戰群儒，魯子敬力排眾議',
        excerpt:'卻說魯肅、孔明辭了玄德、劉琦，登舟望柴桑郡來。二人在舟中共議，魯肅謂孔明曰：「先生見孫將軍，切不可實言曹操兵多將廣。」孔明曰：「不須子敬叮嚀，亮自有'
    }, {
        id:8,
        urlOfPost:'https://www.google.com.tw',
        date:fakeDate,
        categories:[
            {
                name:'分類一',
                url:'https://www.google.com.tw'
            },{
                name:'分類二',
                url:'https://www.google.com.tw'
            },{
                name:'分類三',
                url:'https://www.google.com.tw'
            }
        ],
        tags:[
            {
                name:'標籤一',
                url:'https://www.google.com.tw'
            },{
                name:'標籤二',
                url:'https://www.google.com.tw'
            },{
                name:'標籤三',
                url:'https://www.google.com.tw'
            },{
                name:'標籤一',
                url:'https://www.google.com.tw'
            },{
                name:'標籤二',
                url:'https://www.google.com.tw'
            },{
                name:'標籤三',
                url:'https://www.google.com.tw'
            },{
                name:'標籤一',
                url:'https://www.google.com.tw'
            },{
                name:'標籤二',
                url:'https://www.google.com.tw'
            },{
                name:'標籤三',
                url:'https://www.google.com.tw'
            },{
                name:'標籤一',
                url:'https://www.google.com.tw'
            },{
                name:'標籤二',
                url:'https://www.google.com.tw'
            },{
                name:'標籤三',
                url:'https://www.google.com.tw'
            },{
                name:'標籤一',
                url:'https://www.google.com.tw'
            },{
                name:'標籤二',
                url:'https://www.google.com.tw'
            },{
                name:'標籤三',
                url:'https://www.google.com.tw'
            }
        ],
        title:'諸葛亮舌戰群儒，魯子敬力排眾議。諸葛亮舌戰群儒，魯子敬力排眾議。諸葛亮舌戰群儒，魯子敬力排眾議。諸葛亮舌戰群儒，魯子敬力排眾議。諸葛亮舌戰群儒，魯子敬力排眾議。諸葛亮舌戰群儒，魯子敬力排眾議',
        excerpt:'卻說魯肅、孔明辭了玄德、劉琦，登舟望柴桑郡來。二人在舟中共議，魯肅謂孔明曰：「先生見孫將軍，切不可實言曹操兵多將廣。」孔明曰：「不須子敬叮嚀，亮自有'
    },
    {
        id:9,
        urlOfPost:'https://www.google.com.tw',
        date:fakeDate,
        categories:[
            {
                name:'分類一',
                url:'https://www.google.com.tw'
            },{
                name:'分類二',
                url:'https://www.google.com.tw'
            },{
                name:'分類三',
                url:'https://www.google.com.tw'
            }
        ],
        title:'諸葛亮舌戰群儒，魯子敬力排眾議',
        imageUrl:'/img/afternoon-tea-time.jpeg'
    }
];